@startuml
title class図
package MenuUI #DDDDDD
{
    class EquipmentMenu
    {
        -Character* Owner
        -Equipmentflag* Equipment
        +void SelectEquipment()
    }  
    class ItemMenu
    {
        -Characer* Owner
        -Itemflag[] Items
        +void SelectItem()
    }
}
class Character
{
    void AddDataTable(item)
    //Item,EquipmentはDataTableで管理
}
EquipmentMenu - Stats.Equipmentclass
EquipmentMenu -up- Character
package Stats #DDDDDD
{
    struct FCharacterStats
    {
    +int Lavel
    +float Exp
        +float HP
        +float MP
        +float AD
        +float AP
        +float AR
        +float MR
        +float FireRes
        +float IceRes
        +float DarkRes
        +float ELecRes
        +float HolyRes
    }


    package "Equipmentclass" #DDDDDD {
        class Equipment
        {
            //DataAssetにて管理
            +FCharacterStats Stats
            +EquipmentComponent
        }
        class Wepon
        {
        }
        class Accessory
        {
        }
        class Armor
        {          
        }
        struct Equipmentflag
        {
            +int Equipmentid
            +EquipmentType type
        }
        class EquipmentComponent
        {
            +void Speciality()
        }
        EquipmentComponent -up-o Equipment
        Equipment -up-|> Wepon 
        Equipment -up-|> Accessory
        Equipment -up-|> Armor
    }

    package "Characterclass" #DDDDDD {
        class StatsComponent
        {
            +FCharacterStats BaseStats
            +FCharacterStats MaxStats
            +FCharacterStats CurrentStats
            +void CaluculateStats()
            +void ApplyDamage(float dagmage)
        }
        class EquipmentComponent
        {
            -Character* Owner
            #Armor* head
            #Armor* Upperbody
            #Armor* lowerbody
            #Wepon* Wepon
            #Accessory* accessory0
            #Accessory* accessory1
            +void Equip(Equipment equipment ,EquipmentType type)
            +void UnEquip()
            +FCharacterStats* EquipmentStats(EquipmentType type)
        }

        EquipmentComponent -up-o StatsComponent
        StatsComponent -up-o Character
        FCharacterStats -up-o StatsComponent
        Equipmentclass -up-o EquipmentComponent 
        FCharacterStats -o Equipment
    } 
}
package GamePlayAbility #DDDDDD
{
    class Ability
    {

    }
}

GamePlayAbility -left- Character

package Item #DDDDDD
{
    class Item
    {
        //できればデータアセットで管理したい
        +void Speciality()
    }
    struct itemflag
    {
        +int Itemid
        +ItemType itemtype
        +int Num
    }
    enum ItemType{
        0:TOOLS
        1:MATERIALS
        2:KEYITEMS
    }
}
Item -right- Character
Item -down- MenuUI.ItemMenu

@enduml
