@startuml
package GamePlayAbility
{
    class MyGamePlayAbility
    {
        #Character* Owner
        #AnimationInstance* anim
        #float damage
        #AbilityTage abiliytag
        +void PlayAnimation()
        +void ApplayDamage()
    }
    enum AbilityFlag
    {
        Ability1=0
        Ability2=(1<<0)
        Ability3=(1<<1)
        ...
    }
}
@endumls